name: uosao
version: 1.0.0
github: "kakakaya/uosao"
license: MIT
author: "kakakaya"
maintainer: "kakakaya@kakakaya.xyz"
copyright: "© kakakaya"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: uosao

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kakakaya/uosao#readme>

ghc-options:
  - -Wall
  # - -Wall-missed-specialisations
  - -Widentities
  # - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissed-specialisations
  # - -Wmissing-export-lists
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  # - -Wmissing-import-lists
  # - -Wmissing-local-signatures
  # - -Wmonomorphism-restriction
  # - -Wpartial-fields
  - -Wredundant-constraints
  - -Wcompat

dependencies:
  - base >= 4.7 && < 5
  - classy-prelude
  - romkan
  - text

executables:
  uosao:
    main: Main.hs
    source-dirs: src
